---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8vent
  namespace: k8vent
  labels:
    app: k8vent
    owner: atomist
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: k8vent
      owner: atomist
  template:
    metadata:
      labels:
        app: k8vent
        owner: atomist
        version: '0'
      annotations:
        atomist.com/repo-image: '[{"container":"k8vent","repo":{"owner":"atomist","name":"k8vent"},"image":"atomist/k8vent"}]'
    spec:
      serviceAccountName: k8vent-serviceaccount
      containers:
      - name: k8vent
        image: atomist/k8vent:0.6.0
        env:
        - name: ATOMIST_ENVIRONMENT
          value: ENV_REPLACE
        - name: K8VENT_WEBHOOKS
          value: https://webhook.atomist.com/atomist/kube/teams/T0REPLACE
        resources:
          limits:
            cpu: 0.1
            memory: 50Mi
          requests:
            cpu: 0.1
            memory: 50Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
